/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceattack;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author arlos
 */
public class GameOver extends javax.swing.JFrame {
    //The gameOver class/Jframe is called when the user "dies" in the game
    //and when the "GameOver" method is called in the "GameSA" class

    //The Pname, Pscore and Ptime variables are given the respective temporary
    //variables from the "TempStorage" class
    String Pname = TempStorage.Name;
    String Pdate;
    int Pscore = TempStorage.Score;
    String Ptime = TempStorage.Time;

    /**
     * Creates new form Menu
     */
    //The gameOver constructor is used to display a new screen that displays the 
    //current players game data and also writes the data to a databsae
    public GameOver() {
        this.setResizable(false);
        initComponents();
        this.setSize(907, 602);
        // Pdate is a variable that gets the current date in String format
        LocalDate now = LocalDate.now();

        System.out.println(Pname);
        Pdate = now.toString();

        //The data of the player is displayed in the respective JLabels
        //The data shows the users final score, name and final time until death
        //Date is not displayed
        score.setText(Integer.toString(Pscore));
        Name.setText(Pname);
        Time.setText(Ptime);

        //The DatabaseWriter method is try-catched to mitigate the IOException
        try {
            DatabaseWriter();
        } catch (IOException ex) {
            Logger.getLogger(GameOver.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //The DatabaseWriter method writes the user data to te text file database
    //All data will be written to one line, seperated by "#"
    //File not found exception is thrown
    public void DatabaseWriter() throws IOException {
        FileWriter fw = null;
        BufferedWriter bw = null;
        PrintWriter pw = null;
        try {
            fw = new FileWriter("DatabaseSA.txt", true);
            bw = new BufferedWriter(fw);
            pw = new PrintWriter(bw);

            pw.println(Pname + "#" + Ptime + "#" + Pscore + "#" + Pdate);

            System.out.println("Success!");
            pw.flush();
        } finally {
            try {
                pw.close();
                bw.close();
                fw.close();
            } catch (IOException e) {
                System.out.println("Error: " + e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        MainMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Score = new javax.swing.JLabel();
        Time3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Name.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        Name.setForeground(new java.awt.Color(0, 204, 51));
        Name.setText("Name");
        jPanel1.add(Name);
        Name.setBounds(380, 10, 260, 40);

        score.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        score.setForeground(new java.awt.Color(0, 204, 51));
        score.setText("Score");
        jPanel1.add(score);
        score.setBounds(440, 50, 150, 50);

        Time.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        Time.setForeground(new java.awt.Color(0, 204, 51));
        Time.setText("Time");
        jPanel1.add(Time);
        Time.setBounds(150, 10, 150, 40);

        MainMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\MainMenu.png")); // NOI18N
        MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainMenuActionPerformed(evt);
            }
        });
        jPanel1.add(MainMenu);
        MainMenu.setBounds(650, 10, 240, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\GameOver.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 561);
        jPanel1.add(Score);
        Score.setBounds(791, 230, 80, 50);

        Time3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Time3.setForeground(new java.awt.Color(0, 204, 51));
        Time3.setText("Time");
        jPanel1.add(Time3);
        Time3.setBounds(150, 10, 150, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainMenuActionPerformed
        // TODO add your handling code here:

        //The MainMenu button takes the user to the main menu screen
        //The current screens visibility is set to false
        this.setVisible(false);
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_MainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameOver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainMenu;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Score;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel Time3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
