/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceattack;

import java.io.IOException;

/**
 *
 * @author arlos
 */
public class HighScores extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public HighScores() {
        //Resizable is set to false and the size of the frame is set to 865, 580
        this.setResizable(false);
        initComponents();
        this.setSize(865, 580);
        //This screen contains all user data(Name, Time, Score, Date)

        //The constructor shows the data as it is in the text file
        //try - catch used to mitigate the file not found exception
        //Throughout this class, instaces of the "DatabaseReader" class is created
        //All data representation and sorting is done in the "DatabaseReader" class and deplayed here.
        try {
            DatabaseReader r = new DatabaseReader();
            TextArea.setText("Name:\tTime:\tScore:\tDate:\n" + r.Show());
        } catch (IOException e) {
            TextArea.setText("File Not Found");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        list1 = new java.awt.List();
        textField1 = new java.awt.TextField();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jFrame2 = new javax.swing.JFrame();
        jFileChooser2 = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        list2 = new java.awt.List();
        label1 = new java.awt.Label();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        canvas1 = new java.awt.Canvas();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jOptionPane1 = new javax.swing.JOptionPane();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        ASC = new javax.swing.JButton();
        Descending = new javax.swing.JButton();
        Alphabetical = new javax.swing.JButton();
        BackH = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        Search = new javax.swing.JButton();
        SearchTXT = new javax.swing.JTextField();
        Recent = new javax.swing.JButton();
        Default = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textField1.setText("textField1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        label1.setText("label1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jScrollPane3.setViewportView(jTree1);

        jScrollPane4.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        ASC.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\ASC.png")); // NOI18N
        ASC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASCActionPerformed(evt);
            }
        });
        jPanel1.add(ASC);
        ASC.setBounds(20, 160, 120, 50);

        Descending.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\DESC.png")); // NOI18N
        Descending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescendingActionPerformed(evt);
            }
        });
        jPanel1.add(Descending);
        Descending.setBounds(20, 240, 140, 50);

        Alphabetical.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\ALP.png")); // NOI18N
        Alphabetical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlphabeticalActionPerformed(evt);
            }
        });
        jPanel1.add(Alphabetical);
        Alphabetical.setBounds(20, 320, 120, 50);

        BackH.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\Back.png")); // NOI18N
        BackH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackHActionPerformed(evt);
            }
        });
        jPanel1.add(BackH);
        BackH.setBounds(20, 20, 140, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\picccc.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 420, 730, 100);

        TextArea.setBackground(new java.awt.Color(0, 0, 0));
        TextArea.setColumns(20);
        TextArea.setFont(new java.awt.Font("Arial Black", 0, 17)); // NOI18N
        TextArea.setForeground(new java.awt.Color(255, 255, 255));
        TextArea.setRows(5);
        jScrollPane5.setViewportView(TextArea);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(160, 130, 540, 280);

        Search.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\Search.png")); // NOI18N
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        jPanel1.add(Search);
        Search.setBounds(700, 310, 140, 50);

        SearchTXT.setBackground(new java.awt.Color(0, 0, 0));
        SearchTXT.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        SearchTXT.setForeground(new java.awt.Color(255, 255, 255));
        SearchTXT.setText("Type");
        jPanel1.add(SearchTXT);
        SearchTXT.setBounds(700, 240, 140, 50);

        Recent.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\Recent.png")); // NOI18N
        Recent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecentActionPerformed(evt);
            }
        });
        jPanel1.add(Recent);
        Recent.setBounds(700, 170, 140, 50);

        Default.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\Default.png")); // NOI18N
        Default.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultActionPerformed(evt);
            }
        });
        jPanel1.add(Default);
        Default.setBounds(680, 20, 160, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\HS.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 856, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ASCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASCActionPerformed
        // TODO add your handling code here:

        //This button allows the user to see the data sorted in ascending order(Score)
        try {
            DatabaseReader d = new DatabaseReader();
            TextArea.setText("Name:\tTime:\tScore:\tDate:\n" + d.Ascending());
        } catch (IOException e) {
            TextArea.setText("File Not Found");
        }

    }//GEN-LAST:event_ASCActionPerformed

    private void DescendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescendingActionPerformed
        // TODO add your handling code here:

        //This button allows the user to see the data sorted in descending order(Score)
        try {
            DatabaseReader d = new DatabaseReader();
            TextArea.setText("Name:\tTime:\tScore:\tDate:\n" + d.Descending());
        } catch (IOException e) {
            TextArea.setText("File Not Found");
        }
    }//GEN-LAST:event_DescendingActionPerformed

    private void AlphabeticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlphabeticalActionPerformed
        // TODO add your handling code here:

        //This button allows the user to see the data sorted in alphabetical order(Name)
        try {
            DatabaseReader d = new DatabaseReader();
            TextArea.setText("Name:\tTime:\tScore:\tDate:\n" + d.Alphabetical());
        } catch (IOException e) {
            TextArea.setText("File Not Found");
        }

    }//GEN-LAST:event_AlphabeticalActionPerformed

    private void BackHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackHActionPerformed
        // TODO add your handling code here:

        //this button allows the user to return to the menu screen
        this.setVisible(false);
        Menu m = new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_BackHActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:

        //This button allows the user to see specified data based on their search and input(Name)
        try {
            DatabaseReader d = new DatabaseReader();
            TextArea.setText("Name:\tTime:\tScore:\tDate:\n" + d.Search(SearchTXT.getText()));
        } catch (IOException e) {
            TextArea.setText("File Not Found");
        }

    }//GEN-LAST:event_SearchActionPerformed

    private void RecentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecentActionPerformed
        // TODO add your handling code here:

        //This button allows the user to see the data sorted according to the most recent players
        //according to date(Date)
        try {
            DatabaseReader d = new DatabaseReader();
            TextArea.setText("Name:\tTime:\tScore:\tDate:\n" + d.Recent());
        } catch (IOException e) {
            TextArea.setText("File Not Found");
        }

    }//GEN-LAST:event_RecentActionPerformed

    private void DefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultActionPerformed
        // TODO add your handling code here:

        //This button allows the user to see the original format of the data (Same as constructor)
        try {
            DatabaseReader r = new DatabaseReader();
            TextArea.setText("Name:\tTime:\tScore:\tDate:\n" + r.Show());
        } catch (IOException e) {
            TextArea.setText("File Not Found");
        }
    }//GEN-LAST:event_DefaultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HighScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HighScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HighScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HighScores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HighScores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ASC;
    private javax.swing.JButton Alphabetical;
    private javax.swing.JButton BackH;
    private javax.swing.JButton Default;
    private javax.swing.JButton Descending;
    private javax.swing.JButton Recent;
    private javax.swing.JButton Search;
    private javax.swing.JTextField SearchTXT;
    private javax.swing.JTextArea TextArea;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTree jTree1;
    private java.awt.Label label1;
    private java.awt.List list1;
    private java.awt.List list2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
