/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceattack;

/**
 *
 * @author arlos
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        //Resizable is set to false and the size of the frame is set to 865,580
        this.setResizable(false);
        initComponents();
        this.setSize(865, 580);
        //Second screen the user see's
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        HS = new javax.swing.JButton();
        PLAY = new javax.swing.JButton();
        Options = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        HS.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\Hsss.png")); // NOI18N
        HS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HSActionPerformed(evt);
            }
        });
        jPanel1.add(HS);
        HS.setBounds(290, 270, 300, 50);

        PLAY.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\Pp.png")); // NOI18N
        PLAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLAYActionPerformed(evt);
            }
        });
        jPanel1.add(PLAY);
        PLAY.setBounds(350, 190, 150, 50);

        Options.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\Op.png")); // NOI18N
        Options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionsActionPerformed(evt);
            }
        });
        jPanel1.add(Options);
        Options.setBounds(320, 360, 210, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\MMM.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 860, 544);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HSActionPerformed
        // TODO add your handling code here:

        //This button sets the menu screens visibility to false and sends the 
        //user to the HighScores screen (Visibility is set to true)
        this.setVisible(false);
        HighScores h = new HighScores();
        h.setVisible(true);
    }//GEN-LAST:event_HSActionPerformed

    private void PLAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLAYActionPerformed
        // TODO add your handling code here:

        //This button sets the menu screens visibility to false and sends the 
        //user to the Tutorial screen (Visibility is set to true)
        this.setVisible(false);
        //Creates a Jframe Object of the Tutorial screen, sets visibility to true
        TutorialScreen P = new TutorialScreen();
        P.setVisible(true);
    }//GEN-LAST:event_PLAYActionPerformed

    private void OptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionsActionPerformed
        // TODO add your handling code here:

        //This button sets the menu screens visibility to false and sends the 
        this.setVisible(false);
        //Creates a Jframe Object of the Options screen, sets visibility to true
        Options o = new Options();
        o.setVisible(true);

    }//GEN-LAST:event_OptionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HS;
    private javax.swing.JButton Options;
    private javax.swing.JButton PLAY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
