/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceattack;

import java.time.LocalDate;
import javax.swing.JFrame;

/**
 *
 * @author arlos
 */
public class Play extends javax.swing.JFrame {

    //The Play class is a screen that allows the user to enter their name.
    //If their name is valid, they are transferred to the GameSA screen
    String Name;

    /**
     * Creates new form Menu
     */
    public Play() {
        //Resizable is set to false
        this.setResizable(false);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        NameTextField = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        Start = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        NameTextField.setBackground(new java.awt.Color(0, 0, 0));
        NameTextField.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        NameTextField.setForeground(new java.awt.Color(255, 255, 255));
        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(NameTextField);
        NameTextField.setBounds(230, 250, 440, 66);

        NameLabel.setBackground(new java.awt.Color(255, 255, 255));
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\Name.png")); // NOI18N
        jPanel1.add(NameLabel);
        NameLabel.setBounds(230, 150, 440, 69);

        Start.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\S.png")); // NOI18N
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        jPanel1.add(Start);
        Start.setBounds(320, 340, 260, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\arlos\\Pictures\\New folder\\Board3.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 880, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
        //The NameTextField allows users to write in the allocated space
    }//GEN-LAST:event_NameTextFieldActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        // TODO add your handling code here:

        //If the Start button is clicked, the data from the NameTextField is
        //returned. If the data/string is null, has more than 15 characters
        //or equal to "Invalid Name!", the text of the NametextField is
        //returned to be "Invalid Name!". These are data validation checks as
        //the player name needs to meet the above mentioned requirments
        //If the name meets the requirments, this screens' visibility is
        //set to false and a new instance of the "GameSA" is created
        //and set visible.
        String s = NameTextField.getText();
        if (s.equals("") | s.length() > 15 | s.equals("Invalid Name!")) {
            NameTextField.setText("Invalid Name!");
        } else {
            Name = s;
            TempStorage.Name = Name;
            this.setVisible(false);
            GameSA t = new GameSA();
            t.setVisible(true);
        }

    }//GEN-LAST:event_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JButton Start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
